//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFTestAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiMatHang
    {
        public int MaLMH { get; set; }
        public string TenLMH { get; set; }
        public byte[] ImageLMH { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> SoHD { get; set; }
    }
}
