//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFTestAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_api_QuangCao
    {
        public int SoHD { get; set; }
        public string MAKO { get; set; }
        public int MaQC { get; set; }
        public System.DateTime NgayBDQC { get; set; }
        public System.DateTime NgayKTQC { get; set; }
        public string NoiDung { get; set; }
        public byte[] ImageQC { get; set; }
        public int ThoiLuong { get; set; }
    }
}
