//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFTestAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_api_DotKhuyenMai
    {
        public int MaKM { get; set; }
        public System.DateTime NgayTao { get; set; }
        public System.DateTime NgayBD { get; set; }
        public System.DateTime NgayKT { get; set; }
        public int SoHD { get; set; }
    }
}
