//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFTestAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_api_ChiTietGiamGiaTheoSL
    {
        public int STT { get; set; }
        public int MaKM { get; set; }
        public int MaMH { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public bool TrangThai { get; set; }
        public int SLMuaToiThieu { get; set; }
        public decimal Giam { get; set; }
    }
}
