//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFTestAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_api_HinhThucThanhToan
    {
        public int MaHTTT { get; set; }
        public string TenHTTT { get; set; }
    }
}
