//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFTestAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_api_BuoiAn
    {
        public int MaBA { get; set; }
        public string TenBA { get; set; }
        public Nullable<System.TimeSpan> GioBD { get; set; }
        public Nullable<System.TimeSpan> GioKT { get; set; }
        public Nullable<int> SoHD { get; set; }
    }
}
